version: "3.9"

services:
  backend:
    build: .
    container_name: yt-dubbing-backend
    ports:
      - "3001:3001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./public:/app/public
      - ./temp:/app/temp
